language: node_js
node_js:
  - 12
directories:
  - node_modules
env:
  - CI=true
  install: npn CI
  script: skip

jobs:
  include:
    - stage: test & lint
      script: npm run test
      script: npm run lint
    